services:
  postgres:
    image: postgres
    container_name: gestao_vagas_postgres
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gestao_vagas

    volumes:
      - gestao_vagas_volume:/var/lib/postgresql/data

volumes:
  gestao_vagas_volume:
    name: gestao_vagas_volume